### ISSUE TITLE
Question about use

### ISSUE THREAD

**Issue by Burnett2k** [codebushi/gatsby-starter-dimension-v2#2]
Hi, sorry for the noob question, but I want to make sure I use this properly. I plan to use this theme for my personal website and I noticed this is an MIT license and the following quote is part of it 

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Does that mean we have to include your license in the footer of the page, or just include the license somewhere in the javascript? I'm new to using MIT license and want to comply, but I'm also a programmer and don't want a footer at the bottom of the page basically saying it was built by someone else.

Please let me know your thoughts

**Comment by ChangoMan** [comment]
You can use this template/design however you like, but the design is by HTML5 UP. You just need to credit them in the footer or something and you're good to use it on anything. https://html5up.net/license
