### ISSUE TITLE
Clicking the scrollbar causes the pop up to disappear

### ISSUE THREAD

**Issue by ghost** [codebushi/gatsby-starter-dimension-v2#3]
The issue I am having is that when I try to scroll down after clicking on a section, it closes out the pop up window and goes back to the home page. I want to be able to scroll up/down freely without the section I have clicked on disappearing.

**Comment by ckygel** [comment]
After hours of searching about... this did the trick. In pages > index.js there's a function for handling click outside. Change it to this so that it's only invoked when the wrapper div is clicked. 
```
  handleClickOutside(event) {
    if (this.wrapperRef && event.target.id == "wrapper") {
      if (this.state.isArticleVisible) {
        this.handleCloseArticle();
      }
    }
  }
```
